In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df = pd.read_csv('drug200.csv')

In [4]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [7]:
df.isnull().mean()*100

Age            0.0
Sex            0.0
BP             0.0
Cholesterol    0.0
Na_to_K        0.0
Drug           0.0
dtype: float64

In [8]:
for i in df.columns:
    df[i] = LabelEncoder().fit_transform(df[i])
    

In [10]:
input = df.drop('Drug',axis=1)
output = df['Drug']

In [17]:
x_train,x_test,y_train,y_test = train_test_split(input,output)

In [18]:
nb = MultinomialNB()
nb.fit(x_train,y_train)
prediction = nb.predict(x_test)
print(confusion_matrix(prediction,y_test))
print(classification_report(prediction,y_test))

[[21  2  0  0  4]
 [ 4  2  1  0  1]
 [ 0  2  2  0  1]
 [ 0  0  1  0  1]
 [ 0  0  0  1  7]]
              precision    recall  f1-score   support

           0       0.84      0.78      0.81        27
           1       0.33      0.25      0.29         8
           2       0.50      0.40      0.44         5
           3       0.00      0.00      0.00         2
           4       0.50      0.88      0.64         8

    accuracy                           0.64        50
   macro avg       0.43      0.46      0.43        50
weighted avg       0.64      0.64      0.63        50

